### ISSUE TITLE
pbs update_project fails

### ISSUE THREAD

**Issue by Tuzoff** [PyBossa/app-tagging-pictures#4]
$ pbs update_project
Traceback (most recent call last):
  File "/usr/local/bin/pbs", line 9, in <module>
    load_entry_point('pybossa-pbs==2.3.1', 'console_scripts', 'pbs')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 488, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 474, in main
    self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 775, in invoke
    return self.invoke_subcommand(ctx, cmd, cmd_name, ctx.args[1:])
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 784, in invoke_subcommand
    return cmd.invoke(cmd_ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 676, in invoke
    ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 325, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 325, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pbs.py", line 149, in update_project
    long_description, tutorial)
  File "/usr/local/lib/python2.7/dist-packages/helpers.py", line 116, in _update_project
    with open(results, 'r') as f:
IOError: [Errno 2] No such file or directory: u'results.html'

Here (http://docs.pybossa.com/en/latest/user/pbs.html) it says:
pbs update_project
That command needs to have in the same folder where you are running it, the following files:
template.html
results.html
long_description.md
tutorial.html

But results.html is missing

**Comment by Tuzoff** [comment]
Seems to get fixed by
touch results.html
